2025-01-17 11:56:06,663 Downloading and reading artifact
2025-01-17 11:56:07,422 Splitting data into train and test
Traceback (most recent call last):
  File "/Users/zhijuanzhang/Documents/UdacityCourse/MLOps_P2_Reproducible_Pipeline/Exercise/lesson-2-data-exploration-and-preparation/exercises/exercise_6/starter/run.py", line 124, in <module>
    go(args)
  File "/Users/zhijuanzhang/Documents/UdacityCourse/MLOps_P2_Reproducible_Pipeline/Exercise/lesson-2-data-exploration-and-preparation/exercises/exercise_6/starter/run.py", line 34, in go
    splits["train"], splits["test"] = train_test_split(df, test_size=args.test_size, random_sate=args.random_state,
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mlflow-ecd34dd7c4d59631a93d3f9c3c0828d18c5e73d8/lib/python3.12/site-packages/sklearn/utils/_param_validation.py", line 191, in wrapper
    params = func_sig.bind(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mlflow-ecd34dd7c4d59631a93d3f9c3c0828d18c5e73d8/lib/python3.12/inspect.py", line 3277, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mlflow-ecd34dd7c4d59631a93d3f9c3c0828d18c5e73d8/lib/python3.12/inspect.py", line 3266, in _bind
    raise TypeError(
TypeError: got an unexpected keyword argument 'random_sate'