2025-01-23 16:10:18,818 Downloading and reading test artifact
[34m[1mwandb[39m[22m:   1 of 1 files downloaded.
Traceback (most recent call last):
  File "/Users/zhijuanzhang/Documents/UdacityCourse/MLOps_P2_Reproducible_Pipeline/Exercise/lesson-4-training-validation-experiment-tracking/exercises/exercise_13/starter/run.py", line 99, in <module>
    go(args)
  File "/Users/zhijuanzhang/Documents/UdacityCourse/MLOps_P2_Reproducible_Pipeline/Exercise/lesson-4-training-validation-experiment-tracking/exercises/exercise_13/starter/run.py", line 21, in go
    df = pd.read_csv(test_data_path, low_memory=False)
  File "/opt/anaconda3/envs/mlflow-34b44ee50a2fded840a3200243d41bcc4d33e891/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/anaconda3/envs/mlflow-34b44ee50a2fded840a3200243d41bcc4d33e891/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/anaconda3/envs/mlflow-34b44ee50a2fded840a3200243d41bcc4d33e891/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/anaconda3/envs/mlflow-34b44ee50a2fded840a3200243d41bcc4d33e891/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
  File "/opt/anaconda3/envs/mlflow-34b44ee50a2fded840a3200243d41bcc4d33e891/lib/python3.10/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
IsADirectoryError: [Errno 21] Is a directory: '/Users/zhijuanzhang/Documents/UdacityCourse/MLOps_P2_Reproducible_Pipeline/Exercise/lesson-4-training-validation-experiment-tracking/exercises/exercise_13/starter/artifacts/data_test.csv:v0'